version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  db:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - .Docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "3400:80"
    depends_on:
      - db

  php:
    image: laravel
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"

